modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
issueTrackerURL="https://github.com/SnappyDragon18/Musical-Foxes/issues"

[[mods]]
  modId="musicalfoxes"
  version="1.0.3"
  displayName="Musical Foxes"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/musical-foxes"
  authors="SchnappDragon"
  description='''Lets foxes play goat horns.'''

  [[dependencies.musicalfoxes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
